CREATE DATABASE IF NOT EXISTS petclinic1;

ALTER DATABASE petclinic1
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON petclinic1.* TO 'petclinic@%' IDENTIFIED BY 'petclinic';
